# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home')),
                ('image_name', models.CharField(max_length=50)),
                ('image_caption', models.TextField(max_length=50)),
                ('likes', models.CharField(max_length=25)),
                ('comments', models.TextField(max_length=144)),
            ],
        ),
    ]
