# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_name']},
        ),
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
