# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20181003_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(max_length=144),
        ),
    ]
