# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20181004_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_caption']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(blank=True, max_length=144),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/'),
        ),
    ]
