# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20181005_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default=True, max_length=144),
        ),
    ]
