# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
