# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_auto_20181006_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(default=True, max_length=25),
        ),
    ]
